# Generated by Django 4.1.7 on 2023-03-21 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_remove_course_average_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='https://st3.depositphotos.com/6672868/13701/v/600/…37014128-stock-illustration-user-profile-icon.jpg', upload_to='uploads/'),
        ),
    ]
