# Generated by Django 4.1.7 on 2023-03-21 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='profile_picture',
            field=models.ImageField(default='', upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='/static/images/placeholder.jpg', upload_to='uploads/'),
        ),
    ]
