# Generated by Django 4.1.7 on 2023-02-25 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('par', models.IntegerField()),
                ('price', models.IntegerField()),
                ('average_rating', models.IntegerField()),
            ],
        ),
    ]
